services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    command: sleep infinity
    ports:
      - published: 80
        target: 80
      - published: 8080
        target: 8080
    volumes:
      - ../..:/workspace:cached